import { IFeatureRequest } from 'shared/types';

export const mockFeatureRequests: IFeatureRequest[] = [
  {
    id: 'feat-1',
    title: 'User Authentication System',
    organizationId: 'org-1',
    createdBy: 'user-1',
    assignedTo: 'user-2',
    status: 'completed',
    initialContext: 'Need a secure way for users to login and manage their accounts',
    conversationId: 'conv-1',
    specDocumentId: 'spec-1',
    openQuestionsCount: 0,
    lastActivityAt: new Date('2024-11-01'),
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'feat-2',
    title: 'Team Invitation Feature',
    organizationId: 'org-1',
    createdBy: 'user-1',
    assignedTo: 'user-2',
    status: 'ready_to_build',
    initialContext: 'Allow admins to invite team members via email',
    conversationId: 'conv-2',
    specDocumentId: 'spec-2',
    targetDate: new Date('2024-12-20'),
    openQuestionsCount: 2,
    lastActivityAt: new Date('2024-12-10'),
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: 'feat-3',
    title: 'Real-time Notifications',
    organizationId: 'org-1',
    createdBy: 'user-1',
    status: 'ready_to_build',
    initialContext: 'Users should get notified when important events happen',
    conversationId: 'conv-3',
    specDocumentId: 'spec-3',
    openQuestionsCount: 0,
    lastActivityAt: new Date('2024-12-09'),
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-12-09'),
  },
  {
    id: 'feat-4',
    title: 'Advanced Search Filters',
    organizationId: 'org-1',
    createdBy: 'user-1',
    status: 'spec_generated',
    initialContext:
      'Add filters for date range, tags, and status to make finding content easier',
    conversationId: 'conv-4',
    specDocumentId: 'spec-4',
    openQuestionsCount: 3,
    lastActivityAt: new Date('2024-12-08'),
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-08'),
  },
  {
    id: 'feat-5',
    title: 'Export Data to CSV',
    organizationId: 'org-1',
    createdBy: 'user-1',
    status: 'spec_generated',
    initialContext: 'Users want to export their data for external analysis',
    conversationId: 'conv-5',
    specDocumentId: 'spec-5',
    openQuestionsCount: 1,
    lastActivityAt: new Date('2024-12-07'),
    createdAt: new Date('2024-12-03'),
    updatedAt: new Date('2024-12-07'),
  },
  {
    id: 'feat-6',
    title: 'Dark Mode Support',
    organizationId: 'org-1',
    createdBy: 'user-1',
    assignedTo: 'user-4',
    status: 'draft',
    initialContext: 'Many users prefer dark mode for reduced eye strain',
    conversationId: 'conv-6',
    openQuestionsCount: 0,
    lastActivityAt: new Date('2024-12-10'),
    createdAt: new Date('2024-12-05'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: 'feat-7',
    title: 'Mobile Responsive Dashboard',
    organizationId: 'org-1',
    createdBy: 'user-1',
    status: 'draft',
    initialContext: 'Dashboard should work well on mobile devices',
    openQuestionsCount: 0,
    lastActivityAt: new Date('2024-12-06'),
    createdAt: new Date('2024-12-06'),
    updatedAt: new Date('2024-12-06'),
  },
  {
    id: 'feat-8',
    title: 'Automated Email Reminders',
    organizationId: 'org-1',
    createdBy: 'user-1',
    status: 'spec_generated',
    conversationId: 'conv-8',
    specDocumentId: 'spec-8',
    openQuestionsCount: 1,
    lastActivityAt: new Date('2024-12-11'),
    createdAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-12-11'),
  },
  {
    id: 'feat-9',
    title: 'Two-Factor Authentication',
    organizationId: 'org-1',
    createdBy: 'user-1',
    assignedTo: 'user-2',
    status: 'ready_to_build',
    initialContext: 'Add extra security layer for sensitive accounts',
    conversationId: 'conv-9',
    specDocumentId: 'spec-9',
    openQuestionsCount: 0,
    lastActivityAt: new Date('2024-12-05'),
    createdAt: new Date('2024-11-18'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'feat-10',
    title: 'Activity Feed',
    organizationId: 'org-1',
    createdBy: 'user-1',
    status: 'spec_generated',
    initialContext: 'Show users what their team has been working on',
    conversationId: 'conv-10',
    specDocumentId: 'spec-10',
    openQuestionsCount: 2,
    lastActivityAt: new Date('2024-12-09'),
    createdAt: new Date('2024-12-02'),
    updatedAt: new Date('2024-12-09'),
  },
  {
    id: 'feat-11',
    title: 'File Upload System',
    organizationId: 'org-1',
    createdBy: 'user-1',
    assignedTo: 'user-4',
    status: 'ready_to_build',
    initialContext: 'Users need to attach files to their projects',
    conversationId: 'conv-11',
    specDocumentId: 'spec-11',
    targetDate: new Date('2024-12-25'),
    openQuestionsCount: 1,
    lastActivityAt: new Date('2024-12-11'),
    createdAt: new Date('2024-11-22'),
    updatedAt: new Date('2024-12-11'),
  },
  {
    id: 'feat-12',
    title: 'API Rate Limiting',
    organizationId: 'org-1',
    createdBy: 'user-1',
    status: 'draft',
    openQuestionsCount: 0,
    lastActivityAt: new Date('2024-12-11'),
    createdAt: new Date('2024-12-11'),
    updatedAt: new Date('2024-12-11'),
  },
];
