import { INotification } from 'shared/types';

export const mockNotifications: INotification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    type: 'question_asked',
    title: 'New question on Team Invitation spec',
    message: 'Mike Johnson asked: "Should we use SendGrid or AWS SES for email sending?"',
    link: '/features/feat-2',
    read: false,
    createdAt: new Date('2024-12-08T10:00:30'),
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    type: 'question_asked',
    title: 'New question on Real-time Notifications spec',
    message: 'Mike Johnson commented: "Why are email notifications excluded?"',
    link: '/features/feat-3',
    read: false,
    createdAt: new Date('2024-12-09T11:00:30'),
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    type: 'status_changed',
    title: 'Feature status updated',
    message: 'Two-Factor Authentication moved to "Ready to Build"',
    link: '/features/feat-9',
    read: true,
    createdAt: new Date('2024-12-05T16:00:00'),
  },
  {
    id: 'notif-4',
    userId: 'user-2',
    type: 'feature_created',
    title: 'New feature request created',
    message: 'Sarah Chen created "Dark Mode Support"',
    link: '/features/feat-6',
    read: true,
    createdAt: new Date('2024-12-05T14:00:00'),
  },
  {
    id: 'notif-5',
    userId: 'user-2',
    type: 'spec_generated',
    title: 'Spec document ready for review',
    message: 'Activity Feed specification has been generated',
    link: '/features/feat-10',
    read: true,
    createdAt: new Date('2024-12-02T16:30:00'),
  },
  {
    id: 'notif-6',
    userId: 'user-1',
    type: 'spec_updated',
    title: 'Spec document updated',
    message: 'Team Invitation spec was updated with new technical considerations',
    link: '/features/feat-2',
    read: true,
    createdAt: new Date('2024-12-07T10:15:00'),
  },
];
